### ISSUE TITLE
Automatic package deployment

### ISSUE THREAD

**Issue by a-slide** [tleonardi/nanocompore#111]
This can be easily implemented using travis for pypi.
It is also doable for conda but it's a little more complicated.
See example in pycoQC https://github.com/a-slide/pycoQC/blob/master/.travis.yml

**Comment by tleonardi** [comment]
I'd leave it manual (with poetry publish) for the moment because we might need to do a few hotfixes to the documentation that don't require a new version on PyPi. We could automate it from release 1.0 onwards ;)
