### ISSUE TITLE
Raw data availability

### ISSUE THREAD

**Issue by vahidAK** [tleonardi/nanocompore#115]
Hi @tleonardi ,

Is your raw data from nanocompore paper available?. in the paper you said is available in ENA with accession PRJEB35148. But I could not find the raw data?

Also, I wanted to know that if your software can be used to detect any types of modifications, as long as there are two samples to do the statistical comparison?

Best,
Vahid.

**Comment by tleonardi** [comment]
Hi @vahidAK,
we are very happy to openly share the data. We had a couple of issues with the data upload to ENA, but these should be solved pretty quickly. Sorry about this.
In the meantime, if you urgently need some specific datasets I'd be happy to send them to you in some other way.

Regarding your second question, yes: Nanocompore can in principle detect any RNA modification as long as: 1) the modification causes a measurable change in the electric signal and 2) you have a control condition that lacks the modification (or is strongly depleted).

Best,
Tom

**Comment by vahidAK** [comment]
Great! thanks a lot @tleonardi ,
Please let me know when the data was available.

Best,
Vahid.

**Comment by tleonardi** [comment]
Hi @vahidAK,
the data is now available on ENA. You can find it under the accession number `PRJEB35148`.
cheers!
tom

**Comment by lpryszcz** [comment]
Hi @tleonardi , is the data still available at ENA? I've check today and `PRJEB35148` lists only FastQ and .cram files. Cheers, 
Leszek

**Comment by tleonardi** [comment]
Hi @lpryszcz,
yes, the fast5 files were converted to cram before uploading them to ENA, as we were told that cram has better compression.
The conversion (both ways) can be done with this tool: https://github.com/EGA-archive/ont2cram

best
tom
