### ISSUE TITLE
database file created by SampComp is not accessible

### ISSUE THREAD

**Issue by amir-azizi** [tleonardi/nanocompore#116]
Hello,

I have followed the instructions in https://nanocompore.rna.rocks/demo/SampComp_usage/ 
The `results` directory contains the following files:
```
out_SampComp.db.bak
out_SampComp.db.dat
out_SampComp.db.dir
out_SampComp.log
out_nanocompore_results.tsv
out_nanocompore_shift_stats.tsv
```

When I tried to generate plots, `SampCompDB` cannot load the "database" file `out_SampComp.db.dat`. I even tried removing `.dat` suffix. This is the error I get:

`NanocomporeError: The result database cannot be opened`

Could you please let me know what I am doing wrong?

Thanks.

**Comment by tleonardi** [comment]
Hi @amir-azizi,
in general, SampCompDB requires the path to out_SampComp.db file, without the .bak/.dat/.dir extension. For example, if your `results` folder was at `/home/user/results` you would call SampCompDB with:
```
db = SampCompDB(db_fn = "/home/user/results/out_SampComp.db")
```

Can you please post the full stack trace and the code block (or line) that's giving you the error?

cheers!

**Comment by amir-azizi** [comment]
Using `out_SampComp.db`, without `.dat` worked. 

Thanks a lot :)

**Comment by tleonardi** [comment]
Perfect, glad it worked!
