### ISSUE TITLE
p values corrected for multi-testing

### ISSUE THREAD

**Issue by Huanle** [tleonardi/nanocompore#124]
Hi @tleonardi ,
Are the p-values in the results of nanocompore already corrected for multi-testing? From the manuscript, it seems to be the case for those values computed by taking into sequence account. 
But is it the same for single-base senario?
Thanks a lot.

**Comment by a-slide** [comment]
Hi @Huanle 
The pValues in the final text report should be adjusted for multiple tests.
I am not sure I understand what you mean by single-base senario.
Ad

**Comment by Huanle** [comment]
Hi @a-slide ,

thanks a lot for yout quick reply.

in the manuscript it says 'Thus, to evaluate the effect of modifications on the proximal sequence context, we implemented an established statistical method that combines the non-independent p-values to produce a combined p-value representative of multiple neighbouring kmers, The p-values are then corrected for multiple tests using Benjamini-Hochberg’s procedure ....‘.
By  single-base, i mean p-values computed for the modification site wtithout accounting for its sequence context (--sequence_context 0).

**Comment by tleonardi** [comment]
Hi @Huanle,
yes, all p-values in the output files are corrected with the BH procedure. This applies both to p-values deriving from the combination of adjacent kmers (_context columns in the output file) as well as to the p-values of individual kmers.
The raw p-values (i.e. prior to BH correction) are stored into the SampCompDB object, if you are interested I can provide info on how to access those.
