### ISSUE TITLE
Output file with list of selected transcripts

### ISSUE THREAD

**Issue by a-slide** [tleonardi/nanocompore#126]
**Is your feature request related to a problem? Please describe.**
When using downsample_high_coverage' option there are currently no easy ways to track which reads have been selected (see https://github.com/tleonardi/nanocompore/issues/125)

**Describe the solution you'd like**
The selected transcripts are stored in a Whitelist object during runtime. It would be easy enough to add an option to the class to output a simple text file with the list of all selected reads and the transcripts they are mapped on.

**Comment by tleonardi** [comment]
This will be solved once we merge #133
