### ISSUE TITLE
What type of signal is plotted

### ISSUE THREAD

**Issue by lingolingolin** [tleonardi/nanocompore#129]
Hi @a-slide @tleonardi ,

I am not clear where the signal values plotted by nanocompore plot_signal function at each reference position come from. https://nanocompore.rna.rocks/demo/SampCompDB_usage/

Because the signals can be either *event_level_mean*  or *samples* associated with the event_leve_mean value from nanopolish eventalign results.
I attached one snapshot of nanopolish eventalign results in order to help making sense of my question.

Thanks a lot. :-)

![image](https://user-images.githubusercontent.com/62891138/80251016-29df0a00-8675-11ea-80ab-c534c45e21fa.png)

**Comment by lingolingolin** [comment]
I looked into the codes. it seems to be the raw signals, i.e., the **samples**.
But how nanocompore treat NNNN and mismatch kmers during statistical analyses and plotting?
Thanks again.

**Comment by a-slide** [comment]
Yes it is the samples median, which is more precise that the event level mean.
NNNN and mismatching kmers are normally skipped in the analyses.

If you want to visualise the proportion of these kmers you can use the `plot_bleeding_hulk` function in SampCompDB API

**Comment by lingolingolin** [comment]
@a-slide ,cool. thanks very much for clarifying it. :-)

**Comment by a-slide** [comment]
NNNNN, mismatching and missing kmers are not used in the statistical test.
Missing kmers are when a the reference kmers is not found in the signal and Nanopolish just skip it
