### ISSUE TITLE
Conda packages for Nanocompore and NanopolishComp

### ISSUE THREAD

**Issue by mmiladi** [tleonardi/nanocompore#131]
Hi @a-slide and @tleonardi ,

We have prepared an initial version of conda packages for Nanocompore and NanopolishComp. They can be found here https://anaconda.org/bioconda/nanocompore and and here https://anaconda.org/bioconda/nanopolishcomp .

There were a few challenges for pinning to the proper dependencies and the versioning are quite relax. So this might make the conda package using another version of libraries than the pip version. It could be that we have missed some critical constraints on the versions. It would be nice if you could check the recipes and/or test the conda packages to see if something needs to change. The recipes can be found here https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nanocompore/meta.yaml and https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nanopolishcomp/meta.yaml  

Best,
Milad

**Comment by a-slide** [comment]
Hi @mmiladi ,
Thanks a lot, I will give it a try as soon as I can.

Adrien

**Comment by tleonardi** [comment]
Hi @mmiladi,
thanks a lot, this is great!!
I'll retry it as well as we will get back to you.

thanks
tom

**Comment by tleonardi** [comment]
Hi @mmiladi,
sorry about the delay. I've tested the installation of the conda packages and they work like a charm! Thanks!

**Comment by mmiladi** [comment]
Wonderful. I have noticed that the scikit version has some impacts on the output messages and the results. If you think some restrictions might be needed, we can add it.
Cheers,
Milad
