### ISSUE TITLE
standard deviation in in silico datasets

### ISSUE THREAD

**Issue by balberti** [tleonardi/nanocompore#141]
Hello Mister Leonardi and Mister Leger,

I'm trying to reproduce the figure 2b of your article relative to nanocompore as part of my internship.
I'm following the different steps from the folder "in_silico dataset" on nanocompore_paper_analyses.
Currently, I would like to create simulated datasets (notebook 03). But I have two questions : 
To generate simulated datasets, what are the standard deviation you used for dwell time shift and intensity shift? In the article, it is written sd from 1 to 4 but in the notebook they are different. Is 1 to 4 only sd names and the real values the ones in the notebook?
Also, how or why did you decide to use these specific values as sd?

Thank you a lot,
Baptiste Alberti

**Comment by tleonardi** [comment]
Hi @balberti,
the faceting labels used in the figure are the actual standard deviation values. The notebook you are referring to is out of date, will push the updated versions as soon as possible.
Thanks for spotting this!
