### ISSUE TITLE
Regarding SampCompDB issues

### ISSUE THREAD

**Issue by aman21392** [tleonardi/nanocompore#143]
Please can you help me how to run SampCompDB through the python API. Beacause i am new in this field. I don't know how to execute python API. Please tell me if there is documents from where i learn how to run in pyhton API. I know its very basic questions but i don't know how to execute this command, and i am stuck in this step now.
Thanks in advance

**Comment by tleonardi** [comment]
Hi @aman21392, we have a [section](https://nanocompore.rna.rocks/demo/SampCompDB_usage/) in the documentation that explains how to use the API, have you had a look at it?

**Comment by aman21392** [comment]
aclab@aclab-HP-Z4-G4-Workstation:~$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nanocompore.SampCompDB import SampCompDB, jhelp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nanocompore'
>>> from nanocompore.SampCompDB import SampCompDB
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nanocompore'

I don't import the packages as you suggested in documentation. so please help me how i import the packages in python
