### ISSUE TITLE
importing error in pyhton API

### ISSUE THREAD

**Issue by aman21392** [tleonardi/nanocompore#144]
aclab@aclab-HP-Z4-G4-Workstation:~$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nanocompore.SampCompDB import SampCompDB, jhelp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nanocompore'

>>> from nanocompore.SampCompDB import SampCompDB
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nanocompore'

I want to import SampCompDB but it gives error please help me to solve this issue.

**Comment by a-slide** [comment]
Hi @aman21392 
It's hard to help you with more information. It just looks like the package is not installed in the virtual environment you are trying to import it from .

**Comment by aman21392** [comment]
Hi @a-slide 
so when we install with pip it not going into virtual environment. It means we have to create first virtual environment for this. If yes, then please suggest me to how to do this if possible.
Thank you in advance

**Comment by a-slide** [comment]
It will go to the virtual env if you activate your env first and then run pip

**Comment by a-slide** [comment]
I will close this as this is not an issue related to Nanocompore
