### ISSUE TITLE
Do you have any software that can replace nanopolish？

### ISSUE THREAD

**Issue by q1134269149** [tleonardi/nanocompore#150]
**Is your feature request related to a problem? Please describe.**

Hi,
    When I prepared to use nanocompore to analysis my data, however, nanopolish installation failed because our server was too old. I used tombo to resquiggle my data, but it do not calculate the eventalign. So I want to know whether there was any other software that could replace nanopolish to complete the data preparation steps. Thanks.
hqin

**Comment by a-slide** [comment]
Ho @q1134269149,
Unfortunatly no. Nanopolish is the only resquiggler supported by nanocompore.
I would maybe recommend to try installing nanopolish using conda: https://anaconda.org/bioconda/nanopolish
Best
Ad
