### ISSUE TITLE
Analyze the nanocompore result

### ISSUE THREAD

**Issue by aman21392** [tleonardi/nanocompore#151]
Hi, I just posted the final results of my nanocompore analysis. But i didn't understand on which basis i consider it m6A modified and unmodified. So please can you help me to sort out this issue. Thanks in advance.
pos	chr	genomicPos	ref_id	strand	ref_kmer	GMM_logit_pvalue	KS_dwell_pvalue	KS_intensity_pvalue	GMM_cov_type	GMM_n_clust	cluster_counts	Logit_LOR
13	NA	NA	ENST00000651669.1	NA	GACGA	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:13/1__Condition2_1:5/0	0.15415067982725816
14	NA	NA	ENST00000651669.1	NA	ACGAC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
15	NA	NA	ENST00000651669.1	NA	CGACC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
16	NA	NA	ENST00000651669.1	NA	GACCT	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
17	NA	NA	ENST00000651669.1	NA	ACCTA	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
18	NA	NA	ENST00000651669.1	NA	CCTAC	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:27/3__Condition2_1:4/2	1.4350845252893225
19	NA	NA	ENST00000651669.1	NA	CTACG	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
20	NA	NA	ENST00000651669.1	NA	TACGC	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:7/23__Condition2_1:4/2	-1.6094379124341005
21	NA	NA	ENST00000651669.1	NA	ACGCA	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
22	NA	NA	ENST00000651669.1	NA	CGCAC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
23	NA	NA	ENST00000651669.1	NA	GCACA	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
24	NA	NA	ENST00000651669.1	NA	CACAC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
25	NA	NA	ENST00000651669.1	NA	ACACG	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
26	NA	NA	ENST00000651669.1	NA	CACGA	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
27	NA	NA	ENST00000651669.1	NA	ACGAG	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:6/24__Condition2_1:1/5	-0.1743533871447777
28	NA	NA	ENST00000651669.1	NA	CGAGA	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:23/6__Condition2_1:6/0	-0.7137664677626812
29	NA	NA	ENST00000651669.1	NA	GAGAA	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
30	NA	NA	ENST00000651669.1	NA	AGAAC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
31	NA	NA	ENST00000651669.1	NA	GAACA	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
32	NA	NA	ENST00000651669.1	NA	AACAT	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
33	NA	NA	ENST00000651669.1	NA	ACATG	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:23/6__Condition2_1:3/3	1.2321436812926319
34	NA	NA	ENST00000651669.1	NA	CATGC	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:8/21__Condition2_1:1/5	0.20479441264601259
35	NA	NA	ENST00000651669.1	NA	ATGCC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
36	NA	NA	ENST00000651669.1	NA	TGCCT	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:21/9__Condition2_1:2/4	1.299282984130261
37	NA	NA	ENST00000651669.1	NA	GCCTC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
38	NA	NA	ENST00000651669.1	NA	CCTCT	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
39	NA	NA	ENST00000651669.1	NA	CTCTC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
40	NA	NA	ENST00000651669.1	NA	TCTCG	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
41	NA	NA	ENST00000651669.1	NA	CTCGC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
42	NA	NA	ENST00000651669.1	NA	TCGCA	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
43	NA	NA	ENST00000651669.1	NA	CGCAA	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:15/14__Condition2_1:4/2	-0.4462871026284194
44	NA	NA	ENST00000651669.1	NA	GCAAA	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:28/1__Condition2_1:6/0	0.7282385003712155
45	NA	NA	ENST00000651669.1	NA	CAAAG	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
46	NA	NA	ENST00000651669.1	NA	AAAGG	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
47	NA	NA	ENST00000651669.1	NA	AAGGA	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
48	NA	NA	ENST00000651669.1	NA	AGGAT	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
49	NA	NA	ENST00000651669.1	NA	GGATC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
50	NA	NA	ENST00000651669.1	NA	GATCT	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
51	NA	NA	ENST00000651669.1	NA	ATCTC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
52	NA	NA	ENST00000651669.1	NA	TCTCC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
53	NA	NA	ENST00000651669.1	NA	CTCCT	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
54	NA	NA	ENST00000651669.1	NA	TCCTT	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
55	NA	NA	ENST00000651669.1	NA	CCTTC	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:9/20__Condition2_1:3/3	-0.7419373447293769
56	NA	NA	ENST00000651669.1	NA	CTTCA	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
57	NA	NA	ENST00000651669.1	NA	TTCAT	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
58	NA	NA	ENST00000651669.1	NA	TCATC	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:21/9__Condition2_1:6/0	-1.1574527886910433
59	NA	NA	ENST00000651669.1	NA	CATCC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
60	NA	NA	ENST00000651669.1	NA	ATCCC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
61	NA	NA	ENST00000651669.1	NA	TCCCT	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
62	NA	NA	ENST00000651669.1	NA	CCCTC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
63	NA	NA	ENST00000651669.1	NA	CCTCT	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:5/25__Condition2_1:1/5	-0.36772478012531673
64	NA	NA	ENST00000651669.1	NA	CTCTC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
65	NA	NA	ENST00000651669.1	NA	TCTCC	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
66	NA	NA	ENST00000651669.1	NA	CTCCA	nan	0.9999999997843159	0.9999995600113659	full	1	NC	NC
67	NA	NA	ENST00000651669.1	NA	TCCAG	0.9997766988324855	0.9999999997843159	0.9999995600113659	full	2	Condition1_1:24/4__Condition2_1:5/0	-0.18232155679395445

**Comment by tleonardi** [comment]
Hi @aman21392,
you should look at the pvalue columns (in particular `GMM_logit_pvalue`). When these p-values are below a significance threshold (e.g. 0.01) you can consider that position to be modified.
Please look at our paper on bioRxiv for info on how these tests are run.
