### ISSUE TITLE
SampComp output is a .dat file

### ISSUE THREAD

**Issue by sr8510** [tleonardi/nanocompore#177]
I am using Nanocompore to analyze RNA modifications in a set of nanopore Direct RNA sequencing samples. I am now comparing 2 samples (I am still preparing the replicates but wanted to check the flow of the code). Each sample has aroun 1 million reads. I performed all the steps in the Nanocompore protocol (Alignment with Minimap, Eventalign then Eventalign collapes). When I perform SampComp, I got the output file as a .db.dat (the file name is out_SampComp.db.dat). When I tried reading the file using SampCompDB, I get this error: NanocomporeError: The result database cannot be opened
How to fix this error, and is it happening because I am using one replicate per condition?

**Comment by tleonardi** [comment]
Hi, the .dat extension is expected. Are you sure you are using the right command to open it with SampCompDB?
Could you post an `ls` of your working directory as well as the python line you are using to open it?
cheers
tom

**Comment by sr8510** [comment]
Hi Tom

I used Jupyter lab to open the db file. The command was:

from nanocompore.SampCompDB import SampCompDB, jhelp
db = SampCompDB (
    db_fn = "/media/sherif/Data/Miniknow/ALkbh1-Direct_RNA/Nanocompore/results/outSampComp.db.dat",
    fasta_fn = "/media/sherif/Data/Miniknow/ALkbh1-Direct_RNA/Nanocompore/rat.fa")
print (db)
print (db.ref_id_list)

I got this error:

2021-01-27 11:56:00.648 | INFO     | nanocompore.SampCompDB:__init__:55 - Loading SampCompDB
2021-01-27 11:56:00.650 | ERROR    | nanocompore.common:__init__:21 - The result database cannot be opened

What can I do to resolve this?

Sherif








**********************************************************************************************

Sherif Rashad, MD, PhD

Assistant professor;

Department of Neurosurgical Engineering and translational Neuroscience,

& Department of Neurosurgery,

Tohoku University Graduate School of Medicine

1-1 Seiryo-machi, Aoba-ku, Sendai 980-8574, Japan

Email: sherif@nsg.med.tohoku.ac.jp , sherif_rashad@hotmail.com

Phone: +81-80-5730-7839, +81-22-717-7230

Researchgate<https://www.researchgate.net/profile/Sherif_Rashad3>  Google scholar<https://scholar.google.co.jp/citations?user=UvgIlQsAAAAJ&hl=en> ORCID<https://orcid.org/0000-0002-4511-6360> Researchmap<https://researchmap.jp/sherifrashad/>
________________________________

**Comment by tleonardi** [comment]
Hi Sherif,
the .dat extension of the DB is not required.
Can you try with the following?

```
db = SampCompDB (
    db_fn = "/media/sherif/Data/Miniknow/ALkbh1-Direct_RNA/Nanocompore/results/outSampComp.db",
    fasta_fn = "/media/sherif/Data/Miniknow/ALkbh1-Direct_RNA/Nanocompore/rat.fa")
```
