### ISSUE TITLE
Version 1.0.3 is shown as version 1.0.2

### ISSUE THREAD

**Issue by wososa** [tleonardi/nanocompore#182]
**Describe the bug**
I used poetry to install nanocompore 1.0.3. However, when I check the version. It showed v1.0.2

**To Reproduce**
`poetry install`
Installing the current project: nanocompore (1.0.3)
`nanocompore --version`
v1.0.2

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by tleonardi** [comment]
Hi @wososa,
that probably happens because you are not running nanocompore from the poetry environment. You could try running `poetry run nanocompore -v` instead. However, the recommended way to install nanocompore is via pip.
