### ISSUE TITLE
About nominal p-values

### ISSUE THREAD

**Issue by wososa** [tleonardi/nanocompore#188]
Hi @a-slide @tleonardi ,

Are all the p-values (i.e., `GMM_logit_pvalue`, `KS_dwell_pvalue`, `KS_intensity_pvalue`) adjusted p-values? Is `GMM_logit_pvalue` equal to `GMM_anova_pvalue`? Since adjusted p-values will be influenced by the number of genes/transcripts/p-values in a given scenario, is there a way to obtain nominal p-values?

Thanks,
Woody

**Comment by tleonardi** [comment]
Hi @wososa,
apologies for the late reply.
Yes, all p-values in the results text file are adjusted. The `GMM_logit_pvalue` and `GMM_anova_pvalue` are not the same thing. You can find details of the two different tests in the Methods of Nanocompore's preprint on [bioRxiv](https://www.biorxiv.org/content/10.1101/843136v1.full) but the recommendation is to stick to the logit test (the Anova test is largely underpowered for normal experimental designs with a small number of replicates).
The nominal p-values are stored inside the SampComp.db, which is a normal python pickle. You can use the [code](https://github.com/tleonardi/nanocompore/blob/62a8bf41712b5355519024786c5ba34b38ae36bb/nanocompore/SampCompDB.py#L130) for the function that does p-value correction as a starting point to extract uncorrected p-values.
