### ISSUE TITLE
swarmplot to visualize each replicate 

### ISSUE THREAD

**Issue by wososa** [tleonardi/nanocompore#191]
**Is your feature request related to a problem? Please describe.**
I have three replicates per condition and the db.plot_signal generated only one plot by mixing three samples together.

**Describe the solution you'd like**
I hope to have three separate plots based on the '--file_list1' and '--file_list1'

**Comment by tleonardi** [comment]
Hi @wososa
sorry but we don't have a function that creates multiple plots of individual samples. They wouldn't be particularly useful for the typical use case of Nanocompore, i.e. comparing samples to detect modifications.

**Comment by tleonardi** [comment]
You might want to check the `split_samples` option ([docs](https://nanocompore.rna.rocks/demo/SampCompDB_usage/#plot_signal)). It doesn't create separate plots but it labels points based on the sample they belong to.
