### ISSUE TITLE
Code and data for Sup. Figure 10

### ISSUE THREAD

**Issue by mbhall88** [tleonardi/nanocompore#194]
Hey guys,

I was wondering if you could point me to the script(s)/data etc. required to produce the Figure S10 from your Nature Comms paper?

This is the Benchmark against other m6A tools on the ime4 KO data.

Basically what I'm looking for is the data that is input to that plot and hopefully a script or something to generate the figure. I had a look on https://github.com/tleonardi/nanocompore_paper_analyses but couldn't find anything that looked like what I was after.

Thanks for the awesome efforts to make this whole pipeline and analysis open and reproducible!

**Comment by tleonardi** [comment]
Hi sorry for the slow reply! The benchmark analysis was quite complex and required a lot of code, so we split it out into its own pipeline and repo:
https://github.com/a-slide/MetaCompore

**Comment by mbhall88** [comment]
Hi @tleonardi. Yes, I've been using MetaCompore - it is a great resource. However, I don't see a script within that pipeline (or data) that would allow me to reproduce Figure S10?
