### ISSUE TITLE
eventalign_collapse error

### ISSUE THREAD

**Issue by rezarahman12** [tleonardi/nanocompore#203]
I have done eventalignment of direct RNA-Seq data using nanopolish, and obtained file eventalign.txt file.
Then I ran nanocompore for eventalignmnet collapse using the below script-

module load nanocompore/1.0.4

nanocompore eventalign_collapse \
-i /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanopol/ko-rep1/eventalign.txt -o /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanocompore/out

**error obtained:**
nanocompore.SuperParser.SuperParserError: Required field `read_name` not found in files `/scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanopol/ko-rep1/eventalign.txt`

**Screenshots**
![image](https://user-images.githubusercontent.com/110575883/194806106-9a70ff41-7c46-428a-8fb3-e946de42da7e.png)

could you please help me to fix this problem?

**Comment by lmulroney** [comment]
Could you also share a screen shot of the last few lines of the log file?

**Comment by rezarahman12** [comment]
Thank you for your quick reply.
Please find the screenshot of last few lines of the log file.
![image](https://user-images.githubusercontent.com/110575883/194853420-bfbaf4dc-a9c3-4963-8cdb-49916eab3281.png)

**Comment by lmulroney** [comment]
Thanks for this. Last request to help debug this issue. Can you also share a screen shot of the first few lines of the nanopolish eventalign file?

**Comment by rezarahman12** [comment]
Hi @lmulroney 
thank you again for your quick response.
please find the first few lines of the eventalignment.txt file obtained through nanopolish.
I do highly appreciate your time and help.
Kind regards
Reza
![image](https://user-images.githubusercontent.com/110575883/194873976-c4f03e22-32a4-4e0e-a6e8-719be4986252.png)

**Comment by lmulroney** [comment]
Did you use the following three optional arguments when you ran nanopolish eventalign?
--print-read-names --samples --scale-events 

These three optional arguments in nanopolish are required for nanocompore to run properly. 

Cheers,
Logan

**Comment by rezarahman12** [comment]
Hi Logan,

Thank you for your kind reply. I will give it a shot considering the above parameters, and let you know.

Kind regards
Reza

**Comment by rezarahman12** [comment]
Hi Logan (@lmulroney ),

I have now added your suggested options, --print-read-names --samples --scale-events , which worked well. Thank you so much for your great help.

Then, I have done the sampcomp step as well. The results section generated three files  namely, out_sampcomp.log, outSampComp.db.dat, outSampComp.db.dir. Now, I'm facing another issue in the SampCompDB step as I'm not good at linux. I followed https://nanocompore.rna.rocks/demo/SampCompDB_usage/#Import-the-package. 
I have submitted a job in HPC using the below script.

#!/bin/bash
#PBS -A UQ-QBI
#PBS -l select=1:ncpus=10:mem=50GB
#PBS -e /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanocompore/results
#PBS -o /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanocompore/results
#PBS -l walltime=24:00:00
#PBS -N result-table

cd $PBS_O_WORKDIR

module load nanocompore/1.0.4

SampCompDB (db_fn = "/scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanocompore/results/outSampComp.db",
    fasta_fn = "/scratch/project_mnt/S0077/xPore/Homo_sapiens.GRCh38.cdna.all.fa")

Now, I'm getting the below error:
########################### Execution Started #############################
JobId:927168.tinmgr2
UserName:s4613408
GroupName:qris-uq
ExecutionHost:tn117c
###############################################################################
/var/spool/pbs/mom_priv/jobs/927168.tinmgr2.SC: line 14: from: command not found
/var/spool/pbs/mom_priv/jobs/927168.tinmgr2.SC: line 16: syntax error near unexpected token `db_fn'
/var/spool/pbs/mom_priv/jobs/927168.tinmgr2.SC: line 16: `SampCompDB (db_fn = "/scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanocompore/results/outSampComp.db",'

Could you please help me to solve this problem as well? I will be very grateful to you as my current project needs to use nanocompore for my nanopore data analysis so need to be successful in learning nanocompore. 

I'm very sorry to take your valuable time.

**Comment by keenhl** [comment]
@rezarahman12 You have to write a python script to access SampCompDB.

**Comment by lmulroney** [comment]
Depending on what data you need from the DB, you can review the annotation here:
https://nanocompore.rna.rocks/demo/SampCompDB_usage/

And if you need examples on how we access the data in the DB, you can review the code in SampCompDB.py
