### ISSUE TITLE
nanocompore to be used for SHAPEseq data

### ISSUE THREAD

**Issue by lpantano** [tleonardi/nanocompore#213]
Hi,

I was wondering if nanocompore could be good to analyze RNA modifications from NAI or DEPC or any other chemical probe that you can treat with the RNA and then do direct RNA sequencing?

I have seen the used of tombo, nanopolish, and this seems could be compatible, but wondering if you have tested already?

Thanks!

**Comment by lmulroney** [comment]
Hi @lpantano,

We have not tested Nanocompore with the various shape reagents (so far as I'm aware), but in principle it should work, so long as the adduct deposited by the chemical modifier doesn't stop the RNA from translocating through the nanopore. I suggest reading this paper as a baseline for what you can expect:

https://www.sciencedirect.com/science/article/pii/S2666979X22000143

The chemical modification will likely alter more than 1 position in raw data space, depending on the size of the adduct deposited. But so long as it fits through the pore and is deposited on enough molecules in the same position, Nanocompore should be able to detect the chemically altered bases.

I hope this helps,
Logan
