### ISSUE TITLE
miCLIP dataset

### ISSUE THREAD

**Issue by kwonej0617** [tleonardi/nanocompore#216]
Hi! I am wondering if you have deposited your miCLIP data on your github page. I checked nanocompore_analysis page but I am not sure which one is. Could you provide it for me?

Thank you!

**Comment by lmulroney** [comment]
Hi @kwonej0617,

That is a really good question. I do not actually have access to those data at the moment. @tleonardi or @a-slide might still have those data, and if they don't answer here in a few days, I would recommend emailing the corresponding authors.

Sorry I couldn't be more helpful,
Logan

**Comment by tleonardi** [comment]
Hi @kwonej0617
the miCLIP data has been uploaded to ENA together with all other datasets and the accession number is reported in the paper.
The miCLIP samples are labelled as MOLM13.
